using System;
using System.Collections.Generic;
using System.Linq;
using Xunit;

public sealed class SpoolmanIntegrationTests
{
    [Fact]
    public void SlicerConfigDetector_ParsesSpoolIds_FromFilamentCustomVariables()
    {
        var lines = new[]
        {
            "; generated by PrusaSlicer",
            "; filament_custom_variables = \"spoolman_id=12;foo=bar\",\"target_spool=34\"",
        };

        var ids = SlicerConfigDetector.TryReadSpoolmanSpoolIds(lines);

        Assert.Equal(2, ids.Count);
        Assert.Equal(12, ids[0]);
        Assert.Equal(34, ids[1]);
    }

    [Fact]
    public void SlicerConfigDetector_ParsesSpoolIds_FromFilamentNotes_WhenCustomVariablesMissing()
    {
        var lines = new[]
        {
            "; filament_notes = spool_id=7;spoolman_id=8",
        };

        var ids = SlicerConfigDetector.TryReadSpoolmanSpoolIds(lines);

        Assert.Equal(2, ids.Count);
        Assert.Equal(7, ids[0]);
        Assert.Equal(8, ids[1]);
    }

    [Fact]
    public void RawMmu_Rewrite_EmitsSetActiveSpool_OnToolchange()
    {
        var lines = new[]
        {
            "; filament_type = PETG;PLA",
            "; filament_custom_variables = \"spoolman_id=12\",\"spoolman_id=34\"",
            "M83",
            "T0",
            "G1 X0 Y0 E10.0",
            "T1",
            "G1 X1 Y1 E1.0",
        };

        var options = DefaultOptions() with
        {
            RawMmuMode = true,
            Firmware = FirmwareFlavor.Klipper,
            FilamentTypes = new[] { "PETG", "PLA" },
            EmitSetActiveSpool = true,
            SpoolmanSpoolIds = new int?[] { 12, 34 },
            // Keep scan/rewrite defaults minimal
            MmuToolchangeWindowLines = 50,
            MmuEOnlyStripThresholdMm = 15,
        };

        var processed = P2ppNetProcessor.ProcessLines(
            lines,
            options,
            displayName: "print.gcode",
            sourcePath: "print.gcode",
            timestampUtc: new DateTime(2025, 12, 27, 0, 0, 0, DateTimeKind.Utc));

        // Toolchange commands stripped
        Assert.DoesNotContain(processed, l => l.Trim().StartsWith("T0", StringComparison.OrdinalIgnoreCase));
        Assert.DoesNotContain(processed, l => l.Trim().StartsWith("T1", StringComparison.OrdinalIgnoreCase));

        // Spoolman macros inserted
        Assert.Contains(processed, l => l.Trim().Equals("SET_ACTIVE_SPOOL ID=12", StringComparison.OrdinalIgnoreCase));
        Assert.Contains(processed, l => l.Trim().Equals("SET_ACTIVE_SPOOL ID=34", StringComparison.OrdinalIgnoreCase));
    }

    [Fact]
    public void RawMmu_Rewrite_DoesNotEmitSetActiveSpool_WhenDisabled()
    {
        var lines = new[]
        {
            "M83",
            "T0",
            "G1 X0 Y0 E10.0",
            "T1",
            "G1 X1 Y1 E1.0",
        };

        var options = DefaultOptions() with
        {
            RawMmuMode = true,
            Firmware = FirmwareFlavor.Klipper,
            EmitSetActiveSpool = false,
            SpoolmanSpoolIds = new int?[] { 12, 34 },
            MmuToolchangeWindowLines = 50,
        };

        var processed = P2ppNetProcessor.ProcessLines(
            lines,
            options,
            displayName: "print.gcode",
            sourcePath: "print.gcode",
            timestampUtc: new DateTime(2025, 12, 27, 0, 0, 0, DateTimeKind.Utc));

        Assert.DoesNotContain(processed, l => l.Trim().StartsWith("SET_ACTIVE_SPOOL", StringComparison.OrdinalIgnoreCase));
    }

    private static Options DefaultOptions() => new(
        InputPath: "in.gcode",
        OutputPath: "out.gcode",
        ShowHelp: false,
        DryRun: false,
        Verbose: false,
        Firmware: FirmwareFlavor.Klipper,
        FilamentTypes: Array.Empty<string>(),
        EmitSetActiveSpool: false,
        SpoolmanSpoolIds: Array.Empty<int?>(),
        RawMmuMode: true,
        PrinterProfileHex: "50325050494e464f",
        AutoloadingOffsetMm: 0,
        MmuToolchangeWindowLines: 200,
        MmuEOnlyStripThresholdMm: 15,
        PingInitialIntervalMm: 350,
        PingMaxIntervalMm: 3000,
        PingLengthMultiplier: 1.03,
        SyncBeforeG4: true,
        G4ZeroToM400: true,
        RewriteM0M1: true,
        DropM0M1AfterO1: true,
        SyncPingMacroOverride: null,
        PingMacroBefore: null,
        PingMacroAfter: null,
        SpliceOffsetMm: 0,
        ExtraEndFilamentMm: 0,
        MinStartSpliceLengthMm: 100,
        MinSpliceLengthMm: 70,
        DefaultAlgorithm: new SpliceAlgorithm(0, 0, 0),
        AlgorithmOverrides: new Dictionary<TransitionKey, SpliceAlgorithm>(),
        DiAlgorithmOverrides: new Dictionary<TransitionKey, SpliceAlgorithm>(),
        MaterialAlgorithmOverrides: new Dictionary<MaterialTransitionKey, SpliceAlgorithm>(),
        OctoPrintStripOmegaCommands: false,
        NoPause: false);
}
